#----------------Dir_settings:----------------------------------------------



main_dir: /mnt/share/ #docs / repository in docker env



genome_dir: genome_input/ # genome data



sample_dir: sample_input/ #sample directory



output_dir: sample_output/ #output folder



logs_dir: logs/ # for logs...



jar_dir: /opt/conda/opt/ #needed for the gatk3_register


#--For--Annotation--------------------------------------------------------------


jar_snpEff: /opt/conda/pkgs/snpeff-4.3.1t-2/share/


jar_SnpSift: /opt/conda/pkgs/snpsift-4.3.1t-1/share/



#---------------Settings:----------------------------------------------



GENOME: resources_broad_hg38_v0_Homo_sapiens_assembly38



KS1: resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf.gz



KS2: resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz



KS3: resources_broad_hg38_v0_1000G_phase1.snps.high_confidence.hg38.vcf.gz



#KS -> KnowSites




TARGET: -L /mnt/share/sample_input/SureSelect_V6_human_all_Exons.bed



TARGET_C: --targets /mnt/share/sample_input/SureSelect_V6_human_all_Exons.bed


#TARGET: ""



COSMIC: --cosmic /mnt/share/genome_input/CosmicCodingMuts.hg38.vcf.gz


#COSMIC: ""
#___________________________Threading_______________________:

BWA_samblaster_sambamba_threads: 1 16

Call_Variants_threads: 1 #2

Normal_VS_Tumor_threads: 1 #8
