#----------------Dir_settings:----------------------------------------------



main_dir: /mnt/share/ #docs / repository in docker env



genome_dir: genome_b37/ # genome data



sample_dir: sample_input/ #sample directory



output_dir: sample_output/ #output folder



logs_dir: logs/ # for logs...



jar_dir: /opt/conda/opt/ #needed for the gatk3_register


#--For--Annotation--------------------------------------------------------------


jar_snpEff: /opt/conda/pkgs/snpeff-4.3.1t-2/share/


jar_SnpSift: /opt/conda/pkgs/snpsift-4.3.1t-1/share/



#---------------Settings:----------------------------------------------



GENOME: b37_human_g1k_v37_decoy.chr20



KS1: b37_dbsnp_138.b37.chr_20p12.1.vcf.gz



KS2: b37_Mills_and_1000G_gold_standard.indels.b37.chr_20p12.1.vcf.gz



KS3: b37_1000G_phase1.indels.b37.chr_20p12.1.vcf.gz



#KS -> KnowSites




TARGET: -L /mnt/share/sample_input/b37.vcrome2.1.ann.chr_20.bed



TARGET_C: --targets /mnt/share/sample_input/b37.vcrome2.1.ann.chr_20.bed


#TARGET: ""



COSMIC: --cosmic /mnt/share/genome_b37/CosmicCodingMuts_v87_12_03_2019.chr_20p12.1.vcf.gz


#COSMIC: ""
#___________________________Threading_______________________:

BWA_samblaster_sambamba_threads: 1 16

Call_Variants_threads: 1 #2

Normal_VS_Tumor_threads: 1 #8
