#----------------Dir_settings:----------------------------------------------



main_dir: /mnt/c/Users/comics/Documents/Laura_Duro/angio_tumor_project/samples/test_1/ #docs / repository in docker env



genome_dir: genome_input/ # genome data



sample_dir: sample_input/ #sample directory



output_dir: sample_output/ #output folder



logs_dir: logs/ # for logs...



jar_dir: /home/comics/miniconda2/opt/ #needed for the gatk3_register


#--For--Annotation--------------------------------------------------------------


jar_snpEff: /opt/conda/pkgs/snpeff-4.3.1t-2/share/


jar_SnpSift: /opt/conda/pkgs/snpsift-4.3.1t-1/share/



#---------------Settings:----------------------------------------------



GENOME: human_g1k_v37



KS1: dbsnp_138.b37.vcf.gz



KS2: Mills_and_1000G_gold_standard.indels.b37.vcf.gz



KS3: 1000G_phase1.snps.high_confidence.b37.vcf.gz



#KS -> KnowSites




TARGET: -L /mnt/c/Users/comics/Documents/Laura_Duro/angio_tumor_project/samples/test_1/sample_input/SureSelect_V6_human_all_Exons.bed



TARGET_C: --targets /mnt/c/Users/comics/Documents/Laura_Duro/angio_tumor_project/samples/test_1/sample_input/SureSelect_V6_human_all_Exons.bed


#TARGET: ""



COSMIC: --cosmic /mnt/c/Users/comics/Documents/Laura_Duro/angio_tumor_project/samples/test_1/genome_input/CosmicCodingMuts_v89_GRCh37.vcf.gz


#COSMIC: ""
#___________________________Threading_______________________:

BWA_samblaster_sambamba_threads: 1 #16

Call_Variants_threads: 1 #2

Normal_VS_Tumor_threads: 1 #8
