#----------------Dir_settings:----------------------------------------------
main_dir: /mnt/share/ #main directory path
genome_dir: genome_input/ # genome data directory
sample_dir: sample_input/ #sample_input directory
output_dir: sample_output/ #sample_output directory
logs_dir: logs/ # for logs
jar_dir: /opt/conda/opt/ #needed for the gatk3_register - do not change
#--For--Annotation--------------------------------------------------------------
jar_snpEff: /opt/conda/pkgs/snpeff-4.3.1t-2/share/
jar_SnpSift: /opt/conda/pkgs/snpsift-4.3.1t-1/share/
#---------------Settings:----------------------------------------------
#genome_input/
GENOME: resources_broad_hg38_v0_Homo_sapiens_assembly38
KS1: resources_broad_hg38_v0_Homo_sapiens_assembly38.vcf.gz 
KS2: resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf
KS3: resources_broad_hg38_v0_1000G_phase1.snps.high_confidence.hg38.vcf
#KS -> KnownSites

#sample_input
TARGET: -L /mnt/share/sample_input/b37.vcrome2.1.ann.chr_20.bed 
TARGET_C: --targets /mnt/share/sample_input/b37.vcrome2.1.ann.chr_20.bed
#TARGET: ""
#genome_input
COSMIC: --cosmic /mnt/share/genome_input/CosmicCodingMuts.hg38.vcf.gz
#COSMIC: ""

#___________________________Threading_______________________:
BWA_samblaster_sambamba_threads: 1 #16
Call_Variants_threads: 1 #2
Normal_VS_Tumor_threads: 1 #8
